#!/usr/bin/env python
import argparse
from util import random_string, CHARSETS

if __name__ == "__main__":
    desc = "Generate a random string using system random"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument(
        "chars",
        metavar="N",
        type=int,
        nargs="?",
        default=10,
        help="Number of characters - default 10",
    )
    parser.add_argument(
        "--charset",
        choices=CHARSETS.keys(),
        default="all",
    )
    args = parser.parse_args()

    print(random_string(args.chars, charset=args.charset))
