#!/usr/bin/python3

import random
import string
import sys

def random_string(length):
    chars = string.ascii_letters + string.digits + '!@$%^&*_|#'
    return ''.join([random.SystemRandom().choice(chars) 
                    for _ in range(length)])
    

if __name__ == "__main__":
    print(random_string(int(sys.argv[1])))
