#!/usr/bin/env python

import argparse
import random
import string

CHARSETS = {
    "alpha": string.ascii_letters,
    "lower": string.ascii_lowercase,
    "upper": string.ascii_uppercase,
    "alphanum": string.ascii_letters + string.digits,
    "all": string.ascii_letters + string.digits + "!@$%^&*_|#",
}


def random_string(length=10, charset="all"):
    chars = CHARSETS[charset]
    return "".join([random.SystemRandom().choice(chars) for _ in range(length)])


if __name__ == "__main__":
    desc = "Generate a random string using system random"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument(
        "chars",
        metavar="N",
        type=int,
        nargs="?",
        default=10,
        help="Number of characters - default 10",
    )
    parser.add_argument(
        "--charset",
        choices=CHARSETS.keys(),
        default="all",
    )
    args = parser.parse_args()

    print(random_string(args.chars, charset=args.charset))
