#! /usr/bin/env bash

PROJECT=${1:?"Please supply the project folder name"}
STATE=${2:?"Specify the project state - local or production"}

sudo ln -s /usr/local/src/${PROJECT}/srv/${STATE}/nginx_${PROJECT}.conf /etc/nginx/sites-enabled/${PROJECT}
sudo ln -s /usr/local/src/${PROJECT}/srv/${STATE}/super_${PROJECT}.conf /etc/supervisor/conf.d/super_${PROJECT}.conf

sudo service nginx reload
sudo supervisorctl reread
sudo supervisorctl update
echo -e "alias re${PROJECT}=\"sudo supervisorctl restart ${PROJECT}\"" >> ~/.bashrc

