#! /usr/bin/env bash

PROJECT=$1
STATE=$2 # local or production
SLUG=$3 # project slug


sudo ln -s /usr/local/src/${PROJECT}/srv/${STATE}/nginx_${PROJECT}.conf /etc/nginx/sites-enabled/${PROJECT}
sudo ln -s /usr/local/src/${PROJECT}/srv/${STATE}/super_${PROJECT}.conf /etc/supervisor/conf.d/super_${PROJECT}.conf

sudo service nginx reload
sudo supervisorctl reread
sudo supervisorctl update
echo -e 'alias re${SLUG}="sudo supervisorctl restart ${PROJECT}"' >> ~/.bashrc
source ~/.bashrc
