#! /usr/bin/env bash
WAGTAIL=0

while :; do
    case $1 in
        -w|--wagtail)
            WAGTAIL=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            break
    esac
done

PROJECT_SLUG=${1:?"You must supply the project abbreviation"}
STATE=${2:?"You must supply the project state - local/dev or production"}

SECRET_KEY=`keygen 50`
DB_PW=`keygen 15`

ENV_ACTIVATE="/usr/local/src/env/${PROJECT_SLUG}/bin/activate"

if [ $WAGTAIL -eq 1 ]
then
    echo -e "\nexport DJANGO_SETTINGS_MODULE='${PROJECT_SLUG}.settings.${STATE}'" >> $ENV_ACTIVATE
else
    echo -e "\nexport DJANGO_SETTINGS_MODULE='config.settings.${STATE}'" >> $ENV_ACTIVATE
fi
echo -e "export ${PROJECT_SLUG}_DB_PW='${DB_PW}'" >> $ENV_ACTIVATE
echo -e "export ${PROJECT_SLUG}_SECRET_KEY='${SECRET_KEY}'" >> $ENV_ACTIVATE
echo -e "alias ${PROJECT_SLUG}env=\"source /usr/local/src/env/${PROJECT_SLUG}/bin/activate\"" >> ~/.bashrc