#! /usr/bin/env bash

PROJECT_ABBR=${1:?"You must supply the project abbreviation"}
ENV_DIR=${2:?"You must supply the name of the environment directory"}
STATE=${3:?"You must supply the project state - local or production"}

SECRET_KEY=`keygen 50`
DB_PW=`keygen 15`

ENV_ACTIVATE="/usr/local/src/env/${ENV_DIR}/bin/activate"

echo -e "\nexport DJANGO_SETTINGS_MODULE='config.settings.${STATE}'" >> $ENV_ACTIVATE
echo -e "export ${PROJECT_ABBR}_DB_PW='${DB_PW}'" >> $ENV_ACTIVATE
echo -e "export ${PROJECT_ABBR}_SECRET_KEY='${SECRET_KEY}'" >> $ENV_ACTIVATE
