#! /usr/bin/env bash

PROJECT_ABBR=$1
ENV_DIR=$2

SECRET_KEY=`keygen 50`
DB_PW=`keygen 15`

ENV_ACTIVATE="/usr/local/src/env/${ENV_DIR}/bin/activate"

echo -e "\nexport DJANGO_SETTINGS_MODULE='config.settings.local'" >> $ENV_ACTIVATE
echo -e "export ${PROJECT_ABBR}_DB_PW='${DB_PW}'" >> $ENV_ACTIVATE
echo -e "export ${PROJECT_ABBR}_SECRET_KEY='${SECRET_KEY}'" >> $ENV_ACTIVATE
