#!/usr/bin/env python

import argparse
import pathlib
import socket

# Variables:
# PROJECT_SLUG   - shorthand name for the project
# PROJECT_USER   - the OS user for the project
# PROJECT_PORT   - the port to host the gunicorn server at

def port_is_open(port):
    s = socket.socket()
    try:
        s.connect(("localhost", port))
    except:
        return False
    else:
        return True

def get_port(start, end):
    """
    Find the first open port between start and end
    """
    for port in range(start, end):
        if port_is_open(port): return port
    return None

def populate(text, context):
    res = text
    for key, value in context.items():
        res = res.replace(key, value)
    return res

if __name__ == "__main__":
    desc = ("Populate template files for server configuration")
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('slug', help="Project Slug")
    parser.add_argument('user', help="OS user for project")
    args = parser.parse_args()
    port = get_port(8001, 9000)
    context = {"PROJECT_SLUG": args["slug"],
               "PROJECT_USER": args["user"],
               "PROJECT_PORT": str(port)}
    templates = pathlib.Path("/home/gabe/bin/templates")
    dest = pathlib.Path(f"/usr/local/src/{args['PROJECT_SLUG']}/srv/local")
    dest.mkdir(exist_ok=True)
    gunicorn_start = populate(open(templates / "gunicorn_start.bash").read(),
                              context)
    nginx = populate(open(templates / "nginx_PROJECT_SLUG.conf"),
                     context)
    supervisor = populate(open(templates / "super_PROJECT_SLUG.conf").read(),
                          context)
    with open(dest / "gunicorn_start.bash", "w") as gunicorn_out:
        gunicorn_out.write(gunicorn_start)
    
    with open(dest / f"nginx_{args['PROJECT_SLUG']}.conf", "w") as nginx_out:
        nginx_out.write(nginx)

    with open(dest / f"super_{args['PROJECT_SLUG']}", "w") as super_out:
        super_out.write(supervisor)
    