#! /usr/bin/env bash

rsync -av --no-group --no-owner --remove-source-files /var/lib/transmission-daemon/downloads/Movies/ /mnt/gabe/seagate26TB/Videos/Movies/
find /var/lib/transmission-daemon/downloads/Movies/ -mindepth 1 -type d -empty -delete

rsync -av --no-group --no-owner --remove-source-files /var/lib/transmission-daemon/downloads/TV\ Shows/ /mnt/gabe/seagate26TB/Videos/TV\ Shows/
find /var/lib/transmission-daemon/downloads/TV\ Shows/ -mindepth 1 -type d -empty -delete