#! /usr/bin/env bash
# USAGE: source unset_dotenv project-slug
PROJECT_SLUG=${1:?"You must supply the project abbreviation"}
ENV_FILE=/usr/local/src/${PROJECT_SLUG}/.env
unset $(grep -Eo "^[A-Za-z0-9_]+" ${ENV_FILE} | xargs)