#! /usr/bin/env bash
source .env
psql ${DB_NAME} -c "GRANT CREATE, CONNECT, TEMPORARY ON DATABASE ${DB_NAME} TO ${DB_USER};"
psql ${DB_NAME} -c "GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};"
psql ${DB_NAME} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};"
psql ${DB_NAME} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${DB_USER};"